server:
  port: 8084

spring:
  application:
    name: supplier-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pharmadb}?currentSchema=procurement
    username: ${DB_USERNAME:pharma}
    password: ${DB_PASSWORD:pharma123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: procurement
  flyway:
    enabled: true
    schemas: procurement
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.pharma: ${LOG_LEVEL:INFO}
